import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const logo = "I didn't say that!";
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col items-center">
          <div className="mt-3 mb-3 w-3/4">
            <h1 className="text-2xl">
              <strong>{logo}</strong>️
            </h1>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
